---

language: python
python:
  - 3.6
  - 3.7
  - 3.8

services:
  - docker

before_install:
  - pip install poetry codecov coverage

install:
  - poetry install --no-root --extras "shinobi-controller cli"

script:
  - coverage run -m unittest discover -v -s shinobi_client/tests

after_success:
  - coverage combine -a
  - coverage report
  - codecov
